branches:
  only:
    - master

environment:
  matrix:
#  - TARGET: i686-pc-windows-msvc
#    MSVC_ARCH: x86
  - TARGET: x86_64-pc-windows-msvc
    MSVC_ARCH: amd64
  - TARGET: i686-pc-windows-gnu
    MSYS2_BITS: 32
  - TARGET: x86_64-pc-windows-gnu
    MSYS2_BITS: 64

install:
  - git submodule update --init --recursive
  - appveyor DownloadFile "https://static.rust-lang.org/dist/rust-nightly-%TARGET%.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - set PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\usr\bin;C:\msys64\mingw%MSYS2_BITS%\bin
  - if defined MSVC_ARCH call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %MSVC_ARCH%
  - rustc -V -v
  - cargo -V -v

build_script:
  - cargo package

test_script:
  - cargo test