branches:
  only:
    - master

environment:
  matrix:
  - TARGET: i686-pc-windows-msvc
    MSVC_ARCH: x86
  - TARGET: x86_64-pc-windows-msvc
    MSVC_ARCH: amd64
  - TARGET: i686-pc-windows-gnu
    MSYS2_BITS: 32
  - TARGET: x86_64-pc-windows-gnu
    MSYS2_BITS: 64
  GH_TOKEN:
    secure: UHajdmalPacLa26ORMDaOwtjJP/U4KOWjlqlHOC/ZFd2wlGscrSq9f7hnpyWWHK0

init:
  - set PATH=C:\Python27;C:\Python27\Scripts;%PATH%;%APPDATA%\Python\Scripts
  - pip install "travis-cargo<0.2" --user
  - appveyor DownloadFile "https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe"
  - rustup-init -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustup default nightly
  - rustc -vV
  - cargo -vV

install:
  - git submodule update --init --recursive
  - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
  - if defined MSVC_ARCH call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %MSVC_ARCH%
  - rustup target add %TARGET%

build_script:
  - cargo doc --no-deps --target %TARGET%
  - cargo package --target %TARGET%

test_script:
  - cargo test --target %TARGET%

deploy_script:
  - if "%TARGET" == "i686-pc-windows-gnu" travis-cargo doc-upload