wrap_comments = true
wrap_match_arms = false
struct_trailing_comma = "Never"
enum_trailing_comma = false
reorder_imports = true
fn_args_density = "Compressed"
where_layout = "HorizontalVertical"
where_indent = "Inherit"
fn_brace_style = "PreferSameLine"
item_brace_style = "PreferSameLine"